language: python
python:
- '3.7'
env:
  global:
  - secure: eVckEatL55k0Tg4nKDzAA1hfjciwGYL9W2+OilGrMu5V6QdpL3E8AMZwyxnF582Rt/OoXwZMqFyhKTRB33OtdXKhjMWgHpi7yw1K/S54wUwVz3XxtRIlOimOj7H9ptqWk/LB/GWMU8isL9xG1mW1PKYQfetRJvsoiAh3zIPCntT0V7V0im8gpd2ZJKPQY81T1eHsX1FWzuPICgvTNFJjzsyf3CgjHwkQGGFbwS5KHQ2y8otZV4MWiRIUfqtOwkjxTXeWABc/QmYE9jziJe8v63dSi+ddPuDMuTE6btDrFTV0Ag9C7fA7oa17HgI37uGbZhv46IuXP9GAp47CsY0ZKWcCZne+HcTWJetVb/Ygy8RkNTnqiAG/IIlOS7cpbG6oqUdo3UZAsWQqD2RzHAMwgvdDnvxPu8Tx3Jf/GmLHYPeaA7dCLSi6t3J0VvIa9O3e/oT39LmOqMnPKtY1lnfIUuG1qQ0t51C7mWYxK1/w9IugGk4tMOGpcEKWlCr2ciHuM3K/TNPOXwWW27bjrv7WgRnzOGjlrk4SefqqqmGC2p+ynKtE8X1j7DjmwJfsDHpGzT++jInbod7lkVnn+P+Gb6fO5BU2wgy1gJZ8EWp+Nf2ylnDvT9/XqUp6Gj7U8q2k0lsDWeomtlrnLYHR12p0DVfEwG/vG3ShiYrfjhjkih0=
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b -p $HOME/miniconda"
- export PATH=$HOME/miniconda/bin:$PATH
- conda config --add channels conda-forge
- conda env create -f environment.yml
- source activate lasif
install:
- cd $TRAVIS_BUILD_DIR; pip install .
script:
- cd $TRAVIS_BUILD_DIR; pytest
- cd $TRAVIS_BUILD_DIR/doc; make html
after_failure:
- wget "https://raw.githubusercontent.com/tremby/imgur.sh/master/imgur.sh"
- find /tmp/pytest-* -name "*.png" | xargs -I % bash imgur.sh %
after_success:
- bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh
